theme: jekyll-theme-cayman

lang: en-US
title: Red Blood Cell 3D-Surface Triangulation
paginate: 1
show_downloads: true
google_analytics:

# About/contact
email: monteirocamponogara@gmail.com
#description: 
author: Lucas Camponogara Viera
github_username: camponogaraviera



